apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../clusters/base/cert-manager/issuers
  - ../../../clusters/base/kyverno/policies
  - ../../../clusters/base/system-upgrade-controller/plans
  - metallb-config.yaml
