apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-operator/
  - ingress/
  - metallb/
  - cert-manager/
  - kyverno/
  - external-secrets/
  - longhorn/
  - monitoring/
  - logging/
  - network-policies/
  - system-upgrade-controller/
