apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  # Set this to your desired k3s version, e.g., v1.30.2+k3s1
  version: v1.30.2+k3s1
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
spec:
  concurrency: 1
  # Ensure masters are upgraded before starting worker upgrades
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  # Must match the server plan version
  version: v1.30.2+k3s1
  upgrade:
    image: rancher/k3s-upgrade
